### ISSUE TITLE
Request-Throttled On Server

### ISSUE THREAD

**Issue by realrhys** [Volentix/venue#116]
Not sure how to look into this one... believe it to be a django thing... In short, I was doing the performance test... to see what would happen,,,, when 'BOOM' the server began throttling the requests... perhaps this is a setting for DNS... would be interesting to discuss....

The output is:: { detail: 'Request was throttled. Expected available in 751 seconds.' }

**Comment by realrhys** [comment]
Thanks Joemar... I did notice that once the timeout is over, and I successfully fullfill the request at /api/retrieve/leaderboard-data/ the next request from the UI.... an additional timeout is required.... weird behaviour for sure.

Weirder still... If I am in a browser that has not had a user sign in... after the timeout, I am able to see the UI, however, if I then use the browser that a user was logged int0 nothing shows up.... but weirder still.... when I return to the brower with no logged in user it also no longer works... obviously this is very bad indeed.

**Comment by realrhys** [comment]
Finally, I do not think that this is the place for throttling for a number of users. If you can simply comment it out and deploy so we can see what happens that would be great... having said that... anything more complicated I would prefer to wait for @sshawn to be part of the conversation.

If its easy to remove/replace please go ahead if you have the time.

Thanks.

**Comment by joemarct** [comment]
@realrhys I think the weird behavior you are observing can be explained by the fact that anonymous users and logged in users have different limits. And also, the behavior will certainly be different when hitting the leaderboard API endpoint as compared to using the leaderboard page in the UI because the requests they send contain different headers, I think they're considered as different users.

Anyway, I think the best way forward is to toggle this throttling on/off using an environment variable, namely `THROTTLE_API_REQUESTS = True/False`. I'll make it `False` by default.

**Comment by realrhys** [comment]
Thanks.... note that now I am experiencing additional issues... I am now getting a 429 error (to many requests) however, the UI remains fine.

@joemarct I am fine with an ENV VAR for now... I  think we need to have this controlled at a different level.
