### ISSUE TITLE
User with referrals shows 200 VTX on leaderboard

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#138]
**Describe the bug**
A user that has referrals shows their referral bounty on the leaderboard when it should not be.

**To Reproduce**
1. Send a referral to a friend.
2. Friend accepts referral.
3. Click on leaderboard
4. See VTX earned in the leaderboard

**Expected behavior**
The VTX earned for a referral should not be displayed in the leaderboard. In fact, the VTX earned by the referral should only be in two places (both of them in screenshots below)

- [ ] The Invite a Friend page
- [ ] The front landing page

**Screenshots**
This should show 0 VTX:
![image](https://user-images.githubusercontent.com/611529/44157298-20b83000-a080-11e8-984c-6f3059c995df.png)

This should show 200 VTX:
![image](https://user-images.githubusercontent.com/611529/44157594-d3888e00-a080-11e8-80b7-1cdb96228ece.png)

This looks good:
![image](https://user-images.githubusercontent.com/611529/44157674-02066900-a081-11e8-97e8-5819c4ce4726.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
n/a

**Comment by Lyncis** [comment]
@shawnlauzon 
- number of tokens in Leaderboard is retrieved from leaderboard-data as total_tokens.
- number of tokens in My Rewards is retrieved from user stats as VTX_Tokens in profile level.

I believe that we need to check how these points are calculated on the back-end because it looks like referral bonus points are added to total_tokens and not added to VTX_Tokens.

**Comment by shawnlauzon** [comment]
That sounds incorrect; should be swapped:

- `leaderboard-data` should return campaign-specific data (not referrals)
- `stats/profile_level` should return overall data (referrals)

So it should be assigned to @alexdashkov
