### ISSUE TITLE
Error registering Copper member level: "User unrecognized ID number not found"

### ISSUE THREAD

**Issue by Jimb0vlabs** [Volentix/venue#144]
Levels that were recognized where as follows:
member
newbie
Levels unrecognized were as follows:
copper member
prompt: User unrecognized ID number not found 

speculation:
The copper level is paid for when you rank as a newbie. I speculate this could be related to the issue but am unsure at this time.

Connects to Volentix/venue-server#202

**Comment by shawnlauzon** [comment]
@Jimb0vlabs I understand the issue here, that Copper member isn't found (and in fact since it's a paid level we will not support it). However, I see the issue says "Levels that were recognized where as follows:
member
newbie" but then on Telegram you said that member was not attempted. Please clarify.

**Comment by Jimb0vlabs** [comment]
"Levels that were recognized where as follows:
member
newbie"
This strictly refers to the BitcoinTalk account ID number verification on Venue.
We are able to access other users ID numbers to test if the other accounts are identified.
The full registration and tracking of a member account has not been tested, only verifying the account ID number.
