### ISSUE TITLE
VTX is awarded but leaderboard shows 0 VTX

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#148]
**Describe the bug**
Even though the user has been awarded points in some screens, the user has 0 VTX.

**To Reproduce**
1. Create a post
2. Wait 5 minutes
3. Expand entry on leaderboard
4. See 0 points in the entry, but 100 points in the detail

**Expected behavior**
Users with points obtained with posts should have a percentage of the VTX.

**Screenshots**
![image](https://user-images.githubusercontent.com/611529/44664621-c2754080-a9e1-11e8-8355-5a760b3e34d4.png)

Also see that current VTX is 0:
![image](https://user-images.githubusercontent.com/611529/44664965-c35aa200-a9e2-11e8-8135-b06fd0765038.png)

**Desktop (please complete the following information):**
Mac / Chrome

**Additional context**
This currently happens on Dev with user "woultries".

I'm guessing that this is a regression from when VTX earned from referrals was separated from VTX earned from the leaderboard.

**UPDATE**: After a few minutes more, I reload the page and the items above are resolved. So there is a delay, probably because of background threads not working correctly.

Just to be clear, if a user earns points through a post, the user should immediately earn VTX. If this does not occur at the same time, the UI will not be consistent and so needs to be fixed.

**Comment by joemarct** [comment]
I have done test on this on the dev but I can't reproduce the inconsistency.

I can imagine though that there's a small window of time that it can happen: when the scraping of forum profiles is finished, only then the computation of points is done, and when the computation of points is done, only then the computation of rankings is done. At the end of that series, only then can the server give the updated number of tokens each user gets.

Except for the scraping, the rest of the chain should be very fast; but while the chain is not finished, there is a chance for the server to give incosistent results between points and tokens credited.

We have two options, either:
1. We fix this server-side by always giving a consistent result (i.e. at the end of the chain of computations)
2. We leave it like that and just inform the users on the client side that such a delay may happen.

I suggest we go for option 2 for now because I think that if we always make the client get fresh leaderboard data, the chance for users to notice this delay will be much much less.

**Comment by shawnlauzon** [comment]
So to summarize:

1. Data is scraped. Database consistent
2. Points are calculated. Database becomes inconsistent.
3. Rankings are calculated. Database still inconsistent.
4. New tokens calculated. Database becomes consistent.

Which means anyone accessing the app between 2 & 4 will see wrong data. 

If we work around this by refreshing data more often as you suggest, we would eventually move to state #4, but also there would be more opportunities to retrieve the data during the time periods 2 & 3. Furthermore, unless the polling was done very fast, the user would still see inconsistent data. So it is not a good solution.

> We fix this server-side by always giving a consistent result (i.e. at the end of the chain of computations)

Yes that is correct, but I would like to know how that would be done. Since each of the steps I imagine store data into the database, it seems like it would be a pretty big change to properly fix this.

**Comment by shawnlauzon** [comment]
From this discussion, it appears that this is not a new problem, and so I'm going to remove the critical flag.
