### ISSUE TITLE
KYC & AML + U.S. & Chinese Restrictions on VENUE

### ISSUE THREAD

**Issue by tk808** [Volentix/venue#189]
This is in regards to when users sign-up, having a disclaimer box and "I accept" that they are going to be required to undergo a KYC and AML check before claiming VTX.

"I accept the KYC and AML checks before I claim VTX into my VERTO Wallet."
"I accept i'm not a resident of the United States or China"

Also that they are not a U.S. or Chinese Resident participating in the bounty campaign. 

This is a high-priority issue, Nemr and i spoke about it in Telegram, please refer to that. The bounty thread on BTT includes these lines of text aswell. 

![untitled](https://user-images.githubusercontent.com/6510751/47970143-34978080-e036-11e8-93ca-fc21a776b032.png)

**Comment by shawnlauzon** [comment]
The signup page currently says that only US persons are not allowed:

![image](https://user-images.githubusercontent.com/611529/48004992-4afa1680-e0e0-11e8-827b-4136348c9a7a.png)

Questions for @tk808 or @papotus (since he gave me the text of the warning box to the right):
1. Should that box on the right be changed to name both U.S. and China? If so, the text is very precisely worded, so I need a new wording to ensure its complete accuracy.
2. I assume that you want those 2 lines above as check boxes which need to be checked to continue. Should the existing "I agree" be a checkbox also?
3. Any other changes on this page?

**Comment by shawnlauzon** [comment]
Done. I have updated the page on UAT: https://venue-uat.volentix.io/signup

Please let me know if you would like any other changes. If not, I will push it to production.

**Comment by shawnlauzon** [comment]
Since I haven't heard from anyone, I assumed that it looked good. I've just promoted to production.
